services:
  web:
    container_name: web
    build: ./web
    ports:
      - '3030:80'  # host:container

  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app/
      - ./data:/data/
