[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump backend version {old_version} -> {new_version}"
tag_message = "backend-{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"app/__version__.py" = ['__version__ = "{version}"']
"README.md" = ["{version}"]
"pyproject.toml" = ['current_version = "{version}"']
